[project]
name = "switch"
version = "0.1.0"
description = "A program to switch between projects"
requires-python = ">=3.11"
dependencies = [
    "argparse",
    "python-ulid",
    "toml",
    "typing-extensions",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
